### ISSUE TITLE
Unhandled Runtime Error：TypeError: A(...).getAsync is not a function

### ISSUE THREAD

**Issue by Bobo100** [vladmandic/human-next#13]
Hello @vladmandic 
**First of all, thank you for developing the Human library. It's been immensely helpful.**

However, I've run into an issue which seems to manifest specifically when using Next.js. Here's the scenario:

I have a default landing page (e.g., homepage) in my Next.js application.
I'm using Next.js's Link component to navigate from the landing page to another page that utilizes the Human library (let's call this the "camera page" is the template in the index.js).
When I navigate directly to the camera page (e.g., by manually entering the URL or refreshing the page), everything works fine.
However, if I navigate to the camera page from the landing page using the Link component, I encounter the following error:

```
webpack-internal:///…/human.esm.js:34802  Uncaught (in promise) TypeError: A(...).getAsync is not a function
at Env.updateBackend (human.esm.js:34788:1)
at getBestBackend (human.esm.js:35431:1)
at check (human.esm.js:35488:1)
at Human.load (human.esm.js:48712:1)
at eval (webpack-internal:///./components/humanComponent/humanComponent.tsx:86:32)
at async importHuman (webpack-internal:///./components/humanComponent/humanComponent.tsx:79:13)
updateBackend @ webpack-internal:///…/human.esm.js:34802
getBestBackend @ webpack-internal:///…/human.esm.js:35445
check @ webpack-internal:///…/human.esm.js:35502
load @ webpack-internal:///…/human.esm.js:48726
eval @ webpack-internal:///…manComponent.tsx:86
await in eval (async)
eval @ webpack-internal:///…manComponent.tsx:77
commitHookEffectListMount @ webpack-internal:///…evelopment.js:23145
commitPassiveMountOnFiber @ webpack-internal:///…evelopment.js:24921
commitPassiveMountEffects_complete @ webpack-internal:///…evelopment.js:24886
commitPassiveMountEffects_begin @ webpack-internal:///…evelopment.js:24873
commitPassiveMountEffects @ webpack-internal:///…evelopment.js:24861
flushPassiveEffectsImpl @ webpack-internal:///…evelopment.js:27034
flushPassiveEffects @ webpack-internal:///…evelopment.js:26979
eval @ webpack-internal:///…evelopment.js:26764
workLoop @ webpack-internal:///….development.js:266
flushWork @ webpack-internal:///….development.js:239
performWorkUntilDeadline @ webpack-internal:///….development.js:533
webpack-internal:///…/human.esm.js:34802  Uncaught (in promise) TypeError: A(...).getAsync is not a function
at Env.updateBackend (human.esm.js:34788:1)
at getBestBackend (human.esm.js:35431:1)
at check (human.esm.js:35488:1)
at Human.load (human.esm.js:48712:1)
at eval (webpack-internal:///./components/humanComponent/humanComponent.tsx:86:32)
at async importHuman (webpack-internal:///./components/humanComponent/humanComponent.tsx:79:13)
updateBackend @ webpack-internal:///…/human.esm.js:34802
getBestBackend @ webpack-internal:///…/human.esm.js:35445
check @ webpack-internal:///…/human.esm.js:35502
load @ webpack-internal:///…/human.esm.js:48726
eval @ webpack-internal:///…manComponent.tsx:86
await in eval (async)
eval @ webpack-internal:///…manComponent.tsx:77
commitHookEffectListMount @ webpack-internal:///…evelopment.js:23145
commitPassiveMountOnFiber @ webpack-internal:///…evelopment.js:24921
commitPassiveMountEffects_complete @ webpack-internal:///…evelopment.js:24886
commitPassiveMountEffects_begin @ webpack-internal:///…evelopment.js:24873
commitPassiveMountEffects @ webpack-internal:///…evelopment.js:24861
flushPassiveEffectsImpl @ webpack-internal:///…evelopment.js:27034
flushPassiveEffects @ webpack-internal:///…evelopment.js:26979
eval @ webpack-internal:///…evelopment.js:26764
workLoop @ webpack-internal:///….development.js:266
flushWork @ webpack-internal:///….development.js:239
performWorkUntilDeadline @ webpack-internal:///….development.js:533
```

Could you provide any insights or potential solutions to address this?
Thank you for your assistance.

**Comment by vladmandic** [comment]
looking at backtrace (its horrible since Next's webpack obfuscates most of it), the only `getAsync` call in `updateBackend` is 
```js
this.wasm.simd = await tf.env().getAsync('WASM_HAS_SIMD_SUPPORT') as boolean;
```
but error `getAsync is not a function` is only possible if `tf` (which is loaded instance of `tfjs` itself) is not initialized.

so you either have multiple instances of tensorflow/js getting loaded somewhere and causing conflict or your usage of `Link` somehow bypasses loading of tensorflow/js to start with.

other than that, really not much i can say.
i'll close the issue as the entire repo `human-next` is just a sample how to use `human` and not directy maintained.
